# -*- coding: utf-8 -*-
"""DistillBERT(IMDB).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtK2eArZoY7wqIU2aDBLn0ioYAJq-9qf
"""

from huggingface_hub import notebook_login

notebook_login()

from datasets import load_dataset

raw_data = load_dataset("imdb")

raw_data

from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification

checkpoint = "distilbert-base-uncased"
tokenizer = DistilBertTokenizerFast.from_pretrained(checkpoint)

model = DistilBertForSequenceClassification.from_pretrained(checkpoint, num_labels = 2)

from transformers import DataCollatorWithPadding

def tokenizer_function(example):
  return tokenizer(example["text"], truncation = True)

tokenized_dataset = raw_data.map(tokenizer_function, batched = True)
data_collator = DataCollatorWithPadding(tokenizer = tokenizer)

tokenized_dataset

tokenized_dataset["train"].shape

split_dataset = tokenized_dataset["train"].train_test_split(test_size = 0.2)
train_dataset = split_dataset["train"]
eval_dataset = split_dataset["test"]

test_dataset = tokenized_dataset["test"]

from transformers import TrainingArguments
import tensorboard
from transformers import EarlyStoppingCallback

trainingArgs = TrainingArguments(
    output_dir="./resultslr",
    report_to="tensorboard",
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=10,
    eval_strategy="steps",
    save_strategy="steps",
    eval_steps=100,
    save_steps=100,
    logging_dir="./logslr",
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    #save_total_limit=2,
    learning_rate=2e-5,
    lr_scheduler_type="linear",
    warmup_ratio=0.06,
    fp16=True,
    push_to_hub=True,
    hub_model_id = "kdrucshi/DistilBERT_IMDB"
)

pip install evaluate

import evaluate
import numpy as np

def compute_metrics(eval_preds):
    accuracy = evaluate.load("accuracy")
    f1 = evaluate.load("f1")

    logits, labels = eval_preds
    predictions = np.argmax(logits, axis=-1)

    acc = accuracy.compute(predictions=predictions, references=labels)
    f1_score = f1.compute(predictions=predictions, references=labels)

    return {"accuracy": acc["accuracy"], "f1": f1_score["f1"]}

from transformers import Trainer

trainer = Trainer(
    model,
    trainingArgs,
    train_dataset = train_dataset,
    eval_dataset = eval_dataset,
    data_collator = data_collator,
    processing_class = tokenizer,
    compute_metrics = compute_metrics,
    callbacks = [EarlyStoppingCallback(early_stopping_patience=3)]
)

trainer.train()

from huggingface_hub import HfApi

api = HfApi()
api.upload_folder(
    repo_id="kdrucshi/DistilBERT_IMDB",
    folder_path="./logslr",
    path_in_repo="tensorboard_logs/"
)

trainer.push_to_hub()

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir ./logslr

trainer.save_model("./results/final_model")
tokenizer.save_pretrained("./results/final_model")

from google.colab import files
import shutil

shutil.make_archive("final_model", 'zip', "./results/final_model")
files.download("final_model.zip")

model = DistilBertForSequenceClassification.from_pretrained("/results/final")

test_dataset

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=trainingArgs,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
    data_collator = data_collator,
)

metrics = trainer.evaluate(test_dataset)
print(metrics)

import pandas as pd

metrics = {
    "accuracy": 0.91,
    "precision": 0.92,
    "recall": 0.90,
    "f1": 0.91,
}

df = pd.DataFrame([metrics])
print(df)

sentence = "Worst day of my life."
input_encode = tokenizer(sentence, truncation = True, padding = True,return_tensors="pt")

import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
input = {k:v.to(device) for k,v in input_encode.items()}

output = model(**input)

print(torch.argmax(output.logits))

print(model.config.label2id)